[tool.poetry]
name = "some-time"
version = "0.1.0"
description = "webapp for time tracking"
authors = ["Absurd Coyote <absurd_coyote@proton.me>"]
license = "GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Flask = "^3.0.3"
Flask-Login = "^0.6.3"
flask-sqlalchemy = "^3.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
